data:
  train_files: /data/training/training_cleaned.json
  val_files: /data/training/math_val.jsonl
  prompt_key: question
  answer_key: std
  image_key: images
  video_key: videos
  image_dir: null
  max_prompt_length: 2048
  max_response_length: 10000
  rollout_batch_size: 128  # equivalent to verl's data.train_batch_size
  mini_rollout_batch_size: null  # equivalent to verl's data.gen_batch_size
  val_batch_size: 128
  override_chat_template: null
  shuffle: false
  seed: 1
  filter_overlong_prompts: true

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2
  online_filtering: false  # dapo filter groups
  filter_key: overall
  filter_low: 0.01
  filter_high: 3.5

worker:
  actor:
    global_batch_size: 64  # equivalent to verl's actor.ppo_mini_batch_size
    micro_batch_size_per_device_for_update: 1  # equivalent to verl's actor.ppo_micro_batch_size_per_gpu
    micro_batch_size_per_device_for_experience: 2  # equivalent to verl's rollout.log_prob_micro_batch_size_per_gpu
    max_grad_norm: 1.0
    padding_free: true
    dynamic_batching: true
    ulysses_size: 1
    model:
      model_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
      enable_gradient_checkpointing: true
      trust_remote_code: true
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw  # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 12
    temperature: 0.6
    top_p: 0.95
    limit_images: 0
    gpu_memory_utilization: 0.7
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 2
    disable_tqdm: false
    val_override_config:
      temperature: 0.6
      top_p: 0.95
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: batch
    reward_function: ./examples/reward_function/math.py:compute_score

trainer:
  total_epochs: 10
  max_steps: 100
  project_name: JET
  experiment_name: 7B_efficient_reasoning_exp
  logger: ["console", "swanlab"]
  nnodes: 1
  n_gpus_per_node: 4
  max_try_make_batch: 20  # -1 means no limit
  val_freq: 20  # -1 to disable
  val_before_train: false
  val_only: false
  val_generations_to_log: 500
  save_freq: 10  # -1 to disable
  save_limit: -1  # -1 to disable
  save_model_only: false
  save_checkpoint_path: ../ckp/7B_exp
  load_checkpoint_path: null
  find_last_checkpoint: true
